version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  db:
    image: postgres:13.8-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092, PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  producer:
    build:
      context: ./Producer
      dockerfile: Dockerfile
    container_name: producer
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: kafka:29092
  consumer:
    build:
      context: ./Consumer
      dockerfile: Dockerfile
    container_name: consumer
    ports:
      - "8081:8081"
    depends_on:
      - db
      - kafka
    environment:
      KAFKA_SERVER: kafka:29092
      DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      DATASOURCE_USERNAME: vlad
      DATASOURCE_PASSWORD: admin
