server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: vlad
    password: admin
    driver-class-name: org.postgresql.Driver
kafka:
  server: localhost:9092